version: '3'

services:
  postgresql_polihack:
    container_name: postgresql_polihack
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=polihackdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5435:5432"
    volumes:
      - polihackdb_data:/var/lib/postgresql/data

volumes:
  polihackdb_data:
